### ISSUE TITLE
npm can't add module due to gyp compilation error. Node 20, Ubuntu 22.04

### ISSUE THREAD

**Issue by oleg31337** [wnynya/Pingus#3]
108 error make: *** [raw.target.mk:113: Release/obj.target/raw/src/raw.o] Error 1
108 error gyp ERR! build error
108 error gyp ERR! stack Error: `make` failed with exit code: 2
108 error gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
108 error gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
108 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
108 error gyp ERR! System Linux 5.15.111-1-pve
108 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
108 error gyp ERR! cwd /opt/pingus/node_modules/raw-socket
108 error gyp ERR! node -v v20.5.1
108 error gyp ERR! node-gyp -v v9.4.0

[2023-10-06T18_57_16_650Z-debug-0.log](https://github.com/wnynya/Pingus/files/12834623/2023-10-06T18_57_16_650Z-debug-0.log)

**Comment by wnynya** [comment]
please try below command to install build-essential

`sudo apt-get install -y build-essential`

after install it, try re install pingus

`npm install pingus`

**Comment by oleg31337** [comment]
that did not work unfortunately, I already had build-essential at latest version :-(

**Comment by oleg31337** [comment]
I found that it is not your package, but raw-socket does not compile on node 20.
it works ok on node 18. Coud you please consider correcting your package.json to reflect that?

**Comment by wnynya** [comment]
oh I don't even think about that.
I add engine version in package.json. I think I need to write another raw-socket package for me to fix this. Thank you for let me know this issue.

**Comment by rotu** [comment]
Upstream raw-socket didn't work for me so I resorted to a fork: https://github.com/wnynya/Pingus/pull/4. Does that branch work for you?

**Comment by u-m-i** [comment]
Hi guys! I've been running in the same problem just few days ago, but found out [this](https://stackoverflow.com/questions/46903002/move-a-module-from-devdependencies-to-dependencies-in-npm-package-json) StackOverflow question and basically the error came because `raw-socket` needs `make`, `gcc` and `python2.7`. I use node v22.14.0 and Ubuntu 24 (yup, I needed to compile `python2.7` from the source to make it work) so the error may not be because of the node version.
